[package]
name = "pong_raylib"
version = "0.1.0"
authors = ["comlarsic"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
raylib = "3.5"
rand = "0.8.3"